version: '3.9'  # so we all have the same pyth version

services:

 db: #database container --> like a separated server that hosts the db
   image: mysql:9.2.0  #version found on the docker hub
   environment:
     MYSQL_USER: "my_user"
     MYSQL_PASSWORD: "my_pwd"
     MYSQL_ROOT_PASSWORD: "root_pwd"
   volumes:
     - $PWD:/mapd-workspace  # --> it, the container, sees the pwd as a volume, as it was an ext volume, and it will be mapped to the same location
   command: --secure_file_priv="/mapd-workspace"

 jupyter: #container that hosts jupyter
   depends_on:
     - db
   image: mapd_notebook
   platform: linux/amd64
   ports:
     - 1234:8888 #port where the jup nb will popo up inside the cont, we're mapping it to my pc port 1234 
   volumes:
     - $PWD:/mapd-workspace #mapd folder will be mounted on the pwd 

#So now it's like having two (virtual) coputer in the same laptop and we'll talk with them via a jup nb published on port 1234 with the content of the folder 
#in which we are lounching them

#So writing 'docker-compose up and then we type localhost:1234 on a browser we should be able to see the local folder, on our local computer, exposed 